name: Build STM32 Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies for building CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libcurl4-openssl-dev \
            libexpat1-dev \
            gettext \
            unzip \
            tar \
            make \
            g++ \
            libtool

      - name: Install CMake 3.26.4
        run: |
          mkdir -p $HOME/Tools/cmake
          cd $HOME/Tools/cmake
          wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4.tar.gz
          tar -xvf cmake-3.26.4.tar.gz
          cd cmake-3.26.4
          ./bootstrap
          make -j$(nproc)
          sudo make install
          cmake --version

      - name: Install ARM GCC Toolchain 10.3-2021.10
        run: |
          mkdir -p $HOME/Tools/gcc-arm
          cd $HOME/Tools/gcc-arm
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -O toolchain.tar.bz2
          tar -xvf toolchain.tar.bz2
          echo "$HOME/Tools/gcc-arm/gcc-arm-none-eabi-10.3-2021.10/bin" >> $GITHUB_PATH
          arm-none-eabi-gcc --version

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build
        run: ./build.sh

      - name: Upload library artifact (.a)
        uses: actions/upload-artifact@v4
        with:
          name: static-library
          path: |
            build/*.a